feat(UX) - Fix open game in a new tab
rommapp/romm pull request #1144
Opened 2024-08-31 20:58 UTC by zurdi15

Since we catch the control/shift keys to enble multi-select feature, a new option to the burger menu was added to open a game in a new tab.

Control + click to open the game in a new tab still works in the ``recently added`` section in the dashboard.

Also teaked a couple of little UI details

2024-08-31 21:01 UTC, zurdi15 commented on frontend/src/components/Gallery/AppBar/Platform/Base.vue
> +.platform-icon {
This was made since some platform icons are hard to see in the dark toolbar background

2024-09-01 03:56 UTC, gantoine requested changes

2024-09-01 03:56 UTC, gantoine commented on frontend/src/components/common/Game/AdminMenu.vue
> +    <v-divider />
Can you remove this change and keep all the others? I like the other tweaks overall 👍🏼

2024-09-01 13:59 UTC, gantoine approved these changes

2024-09-01 14:02 UTC, merged